<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Middlewares\**" />
    <Content Remove="Middlewares\**" />
    <EmbeddedResource Remove="Middlewares\**" />
    <None Remove="Middlewares\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\.DS_Store" />
    <None Include="wwwroot\css\bootstrap\.DS_Store" />
    <None Include="wwwroot\css\css\.DS_Store" />
    <None Include="wwwroot\images\css\.DS_Store" />
    <None Include="wwwroot\images\css\bootstrap\.DS_Store" />
    <None Include="wwwroot\images\css\css\.DS_Store" />
    <None Include="wwwroot\js\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogicLayer\BusinessLogicLayer.csproj" />
    <ProjectReference Include="..\BusinessObject\BusinessObject.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
